### ISSUE TITLE
Dependency on `video_player ^2.7.0` should be made explicit

### ISSUE THREAD

**Issue by laogao** [goxiaoy/flutter_survey_js#103]
When image picker was added via 75ba7410dd4cd5969ae3144634bd9f3d6a18d6e5 , there was an ambiguous transitive dependency on `video_player` that might break client code.

Both `appinio_video_player` and `reactive_image_picker` depend on `video_player` (`^2.4.6` and `^2.6.1`, respectively). And the latest `video_player` is `2.7.0`. Without explicit declaration, dependency resolution on client projects might well end up with `2.6.1`, and `flutter pub get` is happy with that. Yet our `lib/ui/video_widget.dart` implementation requires at least `2.7.0`, otherwise the following error would show up during compilation:

```
: Error: Member not found: 'VideoPlayerController.networkUrl'.
video_widget.dart:20
    _controller = VideoPlayerController.networkUrl(widget.uri);

                                        ^^^^^^^^^^
Failed to compile application.
```

**Comment by goxiaoy** [comment]
clean your `pubspec.lock`

**Comment by laogao** [comment]
@goxiaoy You are right. That's the way to fix it. I'm closing this issue.
