### ISSUE TITLE
Want to send a Pull request

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#104]
Hi,
I have done some changes related to beautification of the survey form and want to send a PR, but I am not able to push my local branch to the server. Please suggest.

**Comment by laogao** [comment]
I think first you need to fork. And then `git clone` the forked repo (from your own github url), `checkout -b <your_branch>`, make necessary changes etc., then create the PR from there.

You may want to checkout https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
