### ISSUE TITLE
required `MultipleText` are not validating.

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#109]
**Describe the bug**
According to SurveyJS behavior, a required `MultipleText` element should not be valid if all of the text values are `null`. If any of the `MultipleText`'s text values are non-`null`, the element should be valid.

Right now, `MultipleText` elements in flutter_survey_js are considered valid, even if all of the element's text values are `null`.

**To Reproduce**
SurveyJs json
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "multipletext",
     "name": "question1",
     "title": "Multiple text",
     "isRequired": true,
     "items": [
      {
       "name": "text1"
      },
      {
       "name": "text2"
      }
     ]
    }
   ]
  }
 ]
}
```
SurveyJs answer
```json
{
}
```

**Expected behavior**
Submitting the survey without entering values to the `MultipleText` element should display errors and not submit successfully.

**Screenshots**
N/a

**Desktop (please complete the following information):**
N/a
**Smartphone (please complete the following information):**
Any
**Additional context**
N/a

**Comment by ChopinDavid** [comment]
I've got this mostly fixed on [this branch](https://github.com/wwt/flutter_survey_js/tree/Issue109), but am struggling to make the `multipleTextBuilder` rebuild to show the error text when validating the form... If anybody knows how to make this work, let me know.

**Comment by goxiaoy** [comment]
rebase on https://github.com/goxiaoy/flutter_survey_js/commit/d4d72bfbcabb1f1d2a3a9467bd62db5f63509a5a and create a PR please
