### ISSUE TITLE
Survey elements are not validating for Matrix type of questions neither while their values getting changed nor when a form submission is attempted

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#112]
Survey elements are not validating for Matrix type of questions neither while their values getting changed nor when a form submission is attempted.

**To Reproduce**
{
 "title": "SISO MALI SURVEY FORM",
 "description": "SISO MALI SURVEY FORM- FOR DEMO",
 "logoFit": "cover",
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL002_A",
     "title": "T002 a: Couverture de la population par l’AMO (Interopérabilité entre le SISo et la base de la CANAM)",
     "requiredErrorText": "Required",
     "validators": [
      {
       "type": "expression"
      }
     ],
     "columns": [
      {
       "name": "ASSURE_AMO~N~M",
       "title": "Homme",
       "cellType": "text",
       "isRequired": true,
       "inputType": "number",
       "min": 100,
       "max": 200
      },
      {
       "name": "ASSURE_AMO~N~F",
       "title": "Femme",
       "cellType": "text",
       "isRequired": true,
       "inputType": "number"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "INPS_A",
       "text": "INPS - Actif "
      },
      {
       "value": "INPS_R ",
       "text": "INPS -Retraité "
      },
      {
       "value": "INPS_AV",
       "text": "INPS -Assurance Volontaire "
      },
      {
       "value": "INPS_AU",
       "text": "INPS -Autres "
      },
      {
       "value": "CMPS_A",
       "text": "CMPS - Actif "
      },
      {
       "value": "CMPS_R",
       "text": "CMPS -Retraité "
      },
      {
       "value": "CMPS_AV",
       "text": "CMPS -Assurance Volontaire "
      },
      {
       "value": "CMPS_AU",
       "text": "CMPS -Autres \t"
      }
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "TABL002_B",
     "title": "T 002 b: Couverture de la population par l’AMO (Pris en charge médicalement)",
     "columns": [
      {
       "name": "ASSURE_AMO_CHARGE_MED~N~M",
       "title": "Homme",
       "cellType": "text"
      },
      {
       "name": "ASSURE_AMO_CHARGE_MED~N~F",
       "title": "Femme",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "INPS_A",
       "text": "INPS - Actif \t"
      },
      {
       "value": "INPS_R",
       "text": "INPS -Retraité "
      },
      {
       "value": "INPS_AV",
       "text": "INPS -Assurance Volontaire "
      },
      {
       "value": "INPS_AU",
       "text": "INPS -Autres \t"
      },
      {
       "value": "CMPS_A",
       "text": "CMPS - Actif "
      },
      {
       "value": "CMPS_R",
       "text": "CMPS - Retraité "
      },
      {
       "value": "CMPS_AV",
       "text": "CMPS - Assurance Volontaire "
      },
      {
       "value": "CMPS_AU",
       "text": "CMPS - Autres \t"
      }
     ]
    }
   ],
   "title": "COUVERTURE DES RISQUES SOCIAUX"
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL003",
     "title": "T003 : Couverture de la population par le RAMED (interopérabilité entre le SISo et la base de l’ANAM) - Nombre",
     "columns": [
      {
       "name": "N~M",
       "title": "Homme",
       "cellType": "text"
      },
      {
       "name": "N~F",
       "title": "Femme",
       "cellType": "text",
       "validators": [
        {
         "type": "numeric",
         "minValue": 0,
         "maxValue": 100
        }
       ]
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "IMMATR_RAMED_INDI",
       "text": "Immatriculés au RAMED-Indigent"
      },
      {
       "value": "IMMATR_RAMED_ADMI_DROI",
       "text": "Immatriculés au RAMED-Admis de droit"
      },
      {
       "value": "IMMATR_PRI_CHARGE_MED_INDIG",
       "text": "Immatriculés pris en charge médicalement-Indigent"
      },
      {
       "value": "IMMATR_PRI_CHARGE_MED_ADMI_DROI",
       "text": "Immatriculés pris en charge médicalement-Admis de droit"
      }
     ]
    }
   ]
  },
  {
   "name": "page4",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL005",
     "title": "T005 : Evolution de la couverture du RAMU",
     "columns": [
      {
       "name": "EVO_COUV_RAMU~N~H",
       "title": "Homme",
       "cellType": "text"
      },
      {
       "name": "EVO_COUV_RAMU~N~F",
       "title": "Femme",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "CANAM_CMSS",
       "text": " CANAM - CMSS"
      },
      {
       "value": "CANAM_INPS",
       "text": "CANAM - INPS"
      },
      {
       "value": "ANAM",
       "text": "Anam"
      },
      {
       "value": "MUTUEL",
       "text": "Mutuelle"
      }
     ]
    }
   ]
  },
  {
   "name": "page5",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL006",
     "title": "T006 : Evolution des assurés sociaux des ISS",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "Nouveaux assurés de l’année N (A)-CANAM",
       "text": "Nouveaux assurés de l’année N (A) - CANAM"
      },
      {
       "value": "Nouveaux assurés de l’année N (A)-INPS",
       "text": "Nouveaux assurés de l’année N (A) - INPS"
      },
      {
       "value": "Nouveaux assurés de l’année N (A)-CMSS",
       "text": "Nouveaux assurés de l’année N (A) - CMSS"
      },
      {
       "value": "CUMUL_ASSURE_CANAM",
       "text": "Cumul des assurés N-1 (B) - CANAM"
      },
      {
       "value": "CUMUL_ASSURE_INPS",
       "text": "Cumul des assurés N-1 (B) - INPS"
      },
      {
       "value": "CUMUL_ASSURE_CMSS",
       "text": "Cumul des assurés N-1 (B) - CMSS"
      }
     ]
    }
   ]
  },
  {
   "name": "page6",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL007",
     "title": "T007 : Evolution des adhésions au régime de l'Assurance Volontaire de l’INPS",
     "columns": [
      {
       "name": "REG_AV~N~M",
       "title": "Homme",
       "cellType": "text"
      },
      {
       "name": "REG_AV~N~F",
       "title": "Femme",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "NOUVEAU_ADHEREN_ANNE_COURS",
       "text": " Nouveaux adhérents de l’année en cours"
      }
     ]
    }
   ]
  },
  {
   "name": "page7",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL008 a",
     "title": "T008a : Situation du personnel employé par les organisations de l’ESS (Nombre)",
     "columns": [
      {
       "name": "ASACO~N~T",
       "title": "ASACO",
       "cellType": "text"
      },
      {
       "name": "MUTSOC~N~T",
       "title": "Mutuelles Sociales ",
       "cellType": "text"
      },
      {
       "name": "STECOOP~N~T",
       "title": "Sociétés Coopératives",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "PERS_RECRUT",
       "text": "Personnel recruté"
      },
      {
       "value": "PERS_INSCRI_INPS",
       "text": "Personnel inscrit à l’INPS"
      }
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "TABL008 b",
     "title": "T008b : Situation du personnel employé par les organisations de l’ESS (Cotisation)",
     "columns": [
      {
       "name": "ASACO~FCFA~T",
       "title": "ASACO",
       "cellType": "text"
      },
      {
       "name": "MUTSOC~FCFA~T",
       "title": "Mutuelles Sociales ",
       "cellType": "text"
      },
      {
       "name": "STECOOP~FCFA~T",
       "title": "Sociétés Coopératives",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "MONT_COT_PAR_SOC_PREV",
       "text": "Montant de la cotisation (part sociale) - Prévu"
      },
      {
       "value": "MONT_COT_PAR_SOC_MOB",
       "text": "Montant de la cotisation (part sociale) - Mobilisé"
      }
     ]
    }
   ]
  },
  {
   "name": "page10",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL011",
     "title": "Tableau 011 : Situation des ménages bénéficiaires des transferts sociaux ayant des enfants de 0-5 ans",
     "columns": [
      {
       "name": "N~T",
       "title": "Total"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "cellType": "text",
     "rows": [
      {
       "value": "MENAGE",
       "text": "Nb de ménages"
      },
      {
       "value": "MENAGE_COUVER_PROG_TRANSFER_SOCIA",
       "text": "Nb de ménages couverts par les programmes de transferts sociaux"
      },
      {
       "value": "MENAGE_VICTIM_CHOC_AYAN_BENEF_TRANSFER_SOCIA",
       "text": "Nb de ménages victimes de chocs ayant bénéficié des transferts sociaux"
      },
      {
       "value": "MENAGE_BENEF_TRANSFER_SOCIA_CHEF_FEM",
       "text": "Nb de ménages bénéficiaires des transferts sociaux dont le chef est une femme"
      },
      {
       "value": "MENAGE_BENEF_TRANSFER_SOCIA_AYANT_ENF_0_5ANS",
       "text": "Nb ménages bénéficiaires des transferts sociaux ayant des enfants de 0-5 ans"
      }
     ]
    }
   ]
  },
  {
   "name": "page11",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL012",
     "title": "T012 : Population bénéficiant de socles ou systèmes de protection sociale (Nombre)",
     "columns": [
      {
       "name": "POP_BENEF_SOCLE_SYS_SOC~N~H",
       "title": "Homme",
       "cellType": "text"
      },
      {
       "name": "POP_BENEF_SOCLE_SYS_SOC~N~F",
       "title": "Femme",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "ENFANT",
       "text": "Enfants"
      },
      {
       "value": "CHOMEUR",
       "text": "Chômeurs"
      },
      {
       "value": "PERSON_AGE",
       "text": "Personnes âgées"
      },
      {
       "value": "NOUVE_NE",
       "text": "Nouveaux-nés"
      },
      {
       "value": "VICTIM_ACCIDEN_TRAV",
       "text": "Victimes d’un accident du travail"
      },
      {
       "value": "FEM_ENCEINT",
       "text": "Femmes enceintes"
      }
     ]
    }
   ]
  },
  {
   "name": "page12",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL013",
     "title": "T013 : Couverture des communes par le RSU ",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "COMMUN_COUVERT_RSU",
       "text": "Nb de communes couvertes par le RSU"
      },
      {
       "value": "COMMUN_ENROL_UNIVERSMT_RSU",
       "text": "Nb de Communes enrôlées universellement dans le RSU"
      },
      {
       "value": "COMMUN_DISPOSAN_KIOSQ_RSU",
       "text": "Nb de Communes disposant de Kiosque RSU"
      },
      {
       "value": "MENAGE_ENROL_RSU",
       "text": "Nb de ménages enrôlés dans le RSU (base RSU et autres)"
      }
     ]
    }
   ]
  },
  {
   "name": "page13",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL014",
     "title": "T014 : Formation des agents structures du développement social formés sur le RSU (Nombre)",
     "columns": [
      {
       "name": "STRUC_AGEN~N~T",
       "title": "Agents de la structure",
       "cellType": "text"
      },
      {
       "name": "STRUC_AGEN_FORME_RSU~N~T",
       "title": "Agents formés sur le RSU",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "DNPSES",
      "DNDS",
      "DRDSES",
      "SLDSES",
      "CCDSES"
     ]
    }
   ]
  },
  {
   "name": "page14",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL015",
     "title": "T015 : Communes à risque d’insécurité alimentaire",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "COMMUN_RISQ_INOND_RISQ_INSECU_ALIMENT",
       "text": "Nb de communes à risque d’inondation risque insécurité alimentaire"
      },
      {
       "value": "COMMUNE_RISQ_INOND",
       "text": "Nb de communes à risque d’inondation"
      }
     ]
    }
   ]
  },
  {
   "name": "page15",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL016",
     "title": "T016 : Prise en compte dans le PDESC des activités de protection sociale et de promotion de l’Economie Sociale et Solidaire\t\t\t\t\t\t",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "ACTIV_PROTECTION_SOC_INTEGRE_PDESC",
       "text": "Activités protection sociale intégré dans le PDESC"
      },
      {
       "value": "ACTIV_PROMO_ECONO_SOC_SOLIDA_PDESC",
       "text": "Activités de promotion de l’économie Sociale et Solidaire dans le PDSEC"
      },
      {
       "value": "Nombre de communes ayant intégré au moins une activité du programme 2062 dans le PDSEC",
       "text": "Nb de communes ayant intégré au moins une activité du programme 2.062  dans le PDSEC"
      }
     ]
    }
   ]
  },
  {
   "name": "page16",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL017",
     "title": "T017 : Fonctionnalité des OESS (Sociétés coopératives, ASACO et Mutuelles sociales)",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      },
      {
       "name": "N~FONCTIONNEL",
       "title": "Fonctionnel",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "SCOOP_IMMATRICU",
       "text": "SCOOPS immatriculées"
      },
      {
       "value": "COOP_IMMATRICU",
       "text": "COOP-CA immatriculées\t"
      },
      "ASACO",
      {
       "value": "MUT_SOCIAL",
       "text": "Mutuelles sociales"
      },
      {
       "value": "MUT_SANTE",
       "text": "Mutuelle de Santé"
      }
     ]
    }
   ]
  },
  {
   "name": "page17",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL018",
     "title": "T018 : Représentation des femmes et mise en œuvre de la CAM par les ASACO",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "ASACO_AYANT_30P_F_ORGANE",
       "text": "Nb de ASACO ayant 30% de femmes dans les organes\t"
      },
      {
       "value": "ASACO_PRESIDE_F",
       "text": "Nb de ASACO présidé par une femme\t"
      },
      {
       "value": "ASACO_AYANT_SIGNE_CAM",
       "text": "Nb de ASACO ayant signé la CAM"
      },
      {
       "value": "ASACO_COMITES_PARITAIRE_PLACE",
       "text": "Nb de CP mis en place\t"
      },
      {
       "value": "ASACO_CP_FONCTIONNEL",
       "text": "Nb de CP fonctionnel\t"
      },
      {
       "value": "F_ORGANE_ASACO",
       "text": "Nb de femmes dans les organes des ASACO\t"
      }
     ]
    }
   ]
  },
  {
   "name": "page18",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL019",
     "title": "T019. Organisations de l’Economie Sociale et Solidaire Appuyées (ASACO, mutuelles et sociétés coopératives)\t\t",
     "columns": [
      {
       "name": "ORG_ECO_SOC_SOL~N~T",
       "title": "Total",
       "cellType": "text"
      },
      {
       "name": "ORG_ECO_SOC_SOL_APPUYE~N~T",
       "title": "Appuyé",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "SCOOPS_IMMATRICU",
       "text": "SCOOPS immatriculées\t"
      },
      {
       "value": "COOP_IMMATRICU",
       "text": "COOP-CA immatriculées\t"
      },
      "ASACO",
      {
       "value": "MUT_SANTE",
       "text": "Mutuelles de santé\t"
      },
      {
       "value": "AUTRES_MUT",
       "text": "Autres mutuelles\t"
      },
      {
       "value": "T_OESS",
       "text": "Total OESS\t"
      }
     ]
    }
   ]
  },
  {
   "name": "page19",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL020",
     "title": "T020. Structures de protection sociale et d'économie solidaire Appuyées (construction /réhabilitation, équipement)",
     "columns": [
      {
       "name": "NATURE_APPUI~CONSTRUCTION~N",
       "title": "Nature de l’appui-Construction",
       "cellType": "text"
      },
      {
       "name": "NATURE_APPUI~REHABILITATION~N",
       "title": "Nature de l’appui- Réhabilitation",
       "cellType": "text"
      },
      {
       "name": "NATURE_APPUI~EQUIPEMENT~N",
       "title": "Nature de l’appui- Equipement",
       "cellType": "text"
      },
      {
       "name": "PRINCIPAUX_PARTENAIRES~APPUI",
       "title": "Principaux partenaires d’appui",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "DNPSES",
      "DRDSES",
      "SLDSES",
      "CMSS",
      "INPS",
      "CANAM",
      "ANAM",
      "AMAMUS",
      "CNAPESS",
      "UTM"
     ]
    }
   ]
  },
  {
   "name": "page20",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL021",
     "title": "T021. Transmission de bilan à la tutelle par les Organisations de l’Economie Sociale et Solidaire",
     "columns": [
      {
       "name": "ORG_ECO_SOC_SOL_TRANSMI_BILAN_TUT~N~T",
       "title": "Total",
       "cellType": "text"
      },
      {
       "name": "ORG_ECO_SOC_SOL_TRANSMI_BILAN_TUT~N~FOURNI~BILAN",
       "title": "Ayant fourni de bilan",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "COOP_IMMATRICU",
       "text": "COOP-CA immatriculées\t"
      },
      "ASACO",
      {
       "value": "MUT_SANT",
       "text": "Mutuelles de santé"
      },
      {
       "value": "AUTRE_MUT",
       "text": "Autres Mutuelles\t"
      }
     ]
    }
   ]
  },
  {
   "name": "page21",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL022",
     "title": "T022. Suivi contrôle des sociétés coopératives et des mutuelles",
     "columns": [
      {
       "name": "STE_COOP_ET_MUT_SUIVI_CONT~N~T",
       "title": "Total",
       "cellType": "text"
      },
      {
       "name": "STE_COOP_ET_MUT_SUIVI_CONT~N~SUIVI~CONTROLE",
       "title": "Suivi et contrôlé",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "SCOOP_IMMATRI",
       "text": "SCOOPS immatriculées\t"
      },
      {
       "value": "COOP_CA_IMMATRI",
       "text": "COOP-CA immatriculées\t"
      },
      {
       "value": "MUT_SOCIAL\tMUT_SOCIAL",
       "text": "Mutuelles sociales"
      },
      {
       "value": "MUT_SANTE",
       "text": "Mutuelle de Santé"
      }
     ]
    }
   ]
  },
  {
   "name": "page22",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL023",
     "title": "Tableau 023 : Adhésion, création d’emploi des sociétés coopératives",
     "columns": [
      {
       "name": "N~H",
       "title": "Homme ",
       "cellType": "text"
      },
      {
       "name": "N~F",
       "title": "Femme ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "SCOOPS_SOCIETE_COOP",
       "text": "SCOOPS - Total des sociétés coopératives\t"
      },
      {
       "value": "SCOOPS_MONT_CAPITAL_SOC_INIT_MOB",
       "text": "SCOOPS-  Montant Capital Social Initial mobilisé\t"
      },
      {
       "value": "SCOOPS_EMPLOI_PERM_CREES",
       "text": "SCOOPS-  Nb Emplois Permanents Crées\t"
      },
      {
       "value": "SCOOPS_NOUVEAUX_ADHERENT",
       "text": "SCOOPS -  Nb de nouveaux adhérents\t"
      },
      {
       "value": "SCOOPS_COMITE_GEST",
       "text": "SCOOPS - Comité de Gestion"
      },
      {
       "value": "SCOOPS_COM_SURVEILL",
       "text": "SCOOPS - Commission de Surveillance"
      },
      {
       "value": "COOP_COMITE_GESTION",
       "text": "COOP-CA - Comité de Gestion"
      },
      {
       "value": "COOP_COM_SURVEILL",
       "text": "COOP-CA - Commission de Surveillance"
      }
     ]
    }
   ]
  },
  {
   "name": "page23",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL024",
     "title": "T024 : Formation des membres des sociétés coopératives en Gestion Administrative et Financière (GAF)",
     "columns": [
      {
       "name": "GAF~N~H",
       "title": "Homme  ",
       "cellType": "text"
      },
      {
       "name": "GAF~N~F",
       "title": "Femme ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "MEMBR_ORGANE",
       "text": "Nb de membres des organes"
      },
      {
       "value": "FORMES",
       "text": "Nb formés"
      }
     ]
    }
   ]
  },
  {
   "name": "page24",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL025",
     "title": "T025 : Activités des sociétés coopératives",
     "columns": [
      {
       "name": "N~T",
       "title": "Total ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "AYANT_ACTIVITE_VIABLE_SCOOPS",
       "text": "Nb ayant une activité viable- SCOOPS"
      },
      {
       "value": "AYANT_TENU_4REUNION_SCOOPS",
       "text": "Nb ayant tenu 4 réunions du CA - SCOOPS"
      },
      {
       "value": "AYANT_DEUX_GESTION_COMPTABLE",
       "text": "Nb ayant deux outils de gestion comptables - SCOOPS"
      },
      {
       "value": "AYANT_ACTIVITE_VIABLE_COOP_CA",
       "text": "Nb ayant une activité viable - COOP-CA"
      },
      {
       "value": "AYANT_TENU_4REUNION_CA_COOP_CA",
       "text": "Nb ayant tenu 4 réunions du CA- COOP-CA"
      },
      {
       "value": "AYANT_DEUX_OUTIL_GESTION_COMPTABLE",
       "text": "Nb ayant deux outils de gestion comptables-COOP-CA"
      }
     ],
     "hideIfRowsEmpty": true
    }
   ]
  },
  {
   "name": "page25",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL026 a",
     "title": "T026a : Situation du personnel employé par les organisations",
     "columns": [
      {
       "name": "PERS_RECRU~N~T",
       "title": "Personnel recruté ",
       "cellType": "text"
      },
      {
       "name": "PERS_INSC_INPS~T",
       "title": "Personnel inscrit à l’INPS",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "ASACO",
      {
       "value": "Mutuelles MUT_SOCSociales",
       "text": "Mutuelles Sociales"
      },
      {
       "value": "STE_COOP",
       "text": "Société Coopératives"
      }
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "TABL026 b",
     "title": "T 026b : Situation du personnel employé par les organisations (Montant de cotisation)",
     "columns": [
      {
       "name": "MONT_COT_PREVU~FCFA~T",
       "title": "Cotisation Prévu ",
       "cellType": "text"
      },
      {
       "name": "MONT_COT_MOBILI~FCFA~T",
       "title": "Cotisation Mobilisé ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "ASACO",
      {
       "value": "MUT_SOC",
       "text": "Mutuelles Sociales"
      },
      {
       "value": "STE_COOP",
       "text": "Société Coopérative"
      }
     ]
    }
   ]
  },
  {
   "name": "page26"
  },
  {
   "name": "page27",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL028",
     "title": "T028 : Conformité des mutuelles sociales au règlement N°07-2009/CM/UEMOA",
     "columns": [
      {
       "name": "N~T",
       "title": "Total",
       "cellType": "text"
      },
      {
       "name": "N~F",
       "title": "Femme ",
       "cellType": "text"
      },
      {
       "name": "N~M",
       "title": "Homme ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "T_MUT",
       "text": "Total Mutuelles"
      },
      {
       "value": "MUT_SOCIAL_CONFOR_REGLE",
       "text": "Mutuelles sociales conforme au règlement "
      },
      {
       "value": "MEMB_ORGAN_MUT_SOCIAL_FORME_REGLEMT",
       "text": "Membres des organes des mutuelles sociales formés sur le règlement"
      }
     ]
    }
   ]
  },
  {
   "name": "page28",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL029",
     "title": "T029 : Formation des administrateurs des Organisations de l’Economie Sociale et Solidaire",
     "columns": [
      {
       "name": "ADMIN_FORME~N~M",
       "title": "Hommes formés",
       "cellType": "text"
      },
      {
       "name": "ADMIN_FORME~N~F",
       "title": "Femmes Formées",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "OESS",
      {
       "value": "MUTU_SOCIALE",
       "text": "Mutuelles Sociales"
      },
      "ASACO",
      {
       "value": "STE_COOP",
       "text": "Sociétés Coopératives"
      }
     ]
    }
   ]
  },
  {
   "name": "page29",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "TABL030",
     "title": "Tableau 030 : Fonctionnalité des CFU et des GSAN (Nombre)",
     "columns": [
      {
       "name": "EXISTANT~N~T",
       "title": "Existant ",
       "cellType": "text"
      },
      {
       "name": "FONCTIONNEL~N~T",
       "title": "Fonctionnel ",
       "cellType": "text"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "CFU",
      "GSAN"
     ]
    }
   ]
  }
 ],
 "maxTextLength": 1,
 "maxOthersLength": 8
}

**Expected behavior**
It should prompt or show message while typing.

**Screenshots**
<img width="239" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/5b061cd5-eeee-45d5-882d-18a9050e44ec">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by goxiaoy** [comment]
1. Please provide the minimal reproducable SurveyJs json. The json you provided is too long
2. Expression vlaidator is unsupported currently
3. You are asking about `Matrix` type but questions of ths json you provided are all `matrixdropdown`
4. The result is different in the test ui
    
![image](https://github.com/goxiaoy/flutter_survey_js/assets/8577611/5a708560-56a1-44bb-bdbf-29d9d06235cf)

**Comment by Vpdwivedi** [comment]
Please check the attached screenshot, I took it from your screenshot only. 
1. I had set a range as 100-200 in first cell however this accepts 500 without any error
2. I had set numeric for second cell however this accepts varchar without any error

<img width="455" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/cbef3493-a1d0-44b4-b3c5-ca0fbbd6af59">

Kindly confirm if you need a small JSON for the debugging, I will prepare and share it with you.
