### ISSUE TITLE
`Rating` elements hide number when selected

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#22]
When selecting a value from a `Rating` element, the fill-color and the text-color are the same. We would like to make the text-color of the selected value white so that it is still readable.
<img width="362" alt="Screen Shot 2023-03-20 at 9 18 38 AM" src="https://user-images.githubusercontent.com/27712906/226368116-b2a41340-954b-4f97-961c-52c29a0b178c.png">

**Comment by goxiaoy** [comment]
close via #23
