### ISSUE TITLE
Make `SurveyController` attach to `SurveyProvider`

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#28]
Currently, `SurveyController` is not being attached to `SurveyProvider`. The user can pass `SurveyController` into `SurveyWidget`, but this controller is never actually used. Attaching `SurveyController` to `SurveyProvider` will allow developers to reference the current `SurveyController` off of `context` and use `SurveyController` functionality within the `SurveyWidget`'s `builder`.

**Comment by goxiaoy** [comment]
`SurveyController` should not be used inside `SurveyWidget`
controller expose functions to ancestor widget of `SurveyWidget`
`SurveyWidgetState.of(context)` expose functions to child widget of `SurveyWidget`

**Comment by ChopinDavid** [comment]
You're correct, using `SurveyWidgetState.of(context)` worked for us. I am a bit concerned about having a public `State` that can be referenced from elsewhere in the widget tree. See [this example](https://youtu.be/d_m5csmrf7I?t=503).

**Comment by goxiaoy** [comment]
see https://api.flutter.dev/flutter/widgets/BuildContext/findAncestorStateOfType.html
https://api.flutter.dev/flutter/material/Scaffold/of.html

**Comment by ChopinDavid** [comment]
Interesting, makes sense to me :)
