### ISSUE TITLE
Feature: support `visibleIf` conditions

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#30]
Right now, the framework does not support `visibleIf` conditions.

I have implemented basic `visibleIf` functionality on [this branch](https://github.com/wwt/flutter_survey_js/tree/AddingVisibleIf). There are many things that are not yet supported thus far, such as [built in functions](https://surveyjs.io/form-library/documentation/design-survey/conditional-logic#built-in-functions) as well as condition chaining via `and` and `or`. The code can also be cleaned up quite a bit. Just creating this issue so that I don't forget about all of this.

**Comment by ChopinDavid** [comment]
@laogao @goxiaoy Can either of you see [this branch](https://github.com/wwt/flutter_survey_js/tree/AddingVisibleIf)? The repository is on my company's enterprise account, so I am not sure if people outside of our company can see the changes I made in this branch...

**Comment by laogao** [comment]
> @laogao @goxiaoy Can either of you see [this branch](https://github.com/wwt/flutter_survey_js/tree/AddingVisibleIf)? The repository is on my company's enterprise account, so I am not sure if people outside of our company can see the changes I made in this branch, but I believe you should be able to.
> 
> I am not sure if the commits I made are necessarily the best, so feel free to make suggestions for a more efficient way of parsing visibility logic out of the `visibleIf` property, as well suggestions for adding conditional chaining via `and` and `or`. For example, a `visibleIf` of `{haveKids}='Yes'` or `{kids}>=1` will work, but `{haveKids}='Yes' and {kids}>=1` currently only considers the first condition (I believe).
> 
> I can also make a PR into this main repo if you two think this is something worth adding and improving on.

Can confirm that I'm able to view your branch. Looks good to me and would love to take a deeper dive when time permits. In the mean time, I would add another case which probably quite useful for dealing with checkbox questions (or more precisely, answers) and should be considered as well:

`{someQuesion} anyOf ['abc', 'def']`

Cheers.

**Comment by goxiaoy** [comment]
Blocked by #90

**Comment by ChopinDavid** [comment]
I was able to get single, "unchained" `visibleIf` logic working for our team via [this commit](https://github.com/wwt/flutter_survey_js/commit/a079b82da10259dd53cbb8ec2af955d7f617e460).

It is important to note that this does not handle multiple conditions chained with "AND" or "OR". That would likely require utilizing some PEG parser like the web frameworks do.

I know this is only a half-solution, but if you want me to make a PR, I can go ahead and do that. @goxiaoy
