### ISSUE TITLE
Feature: add ability for checkbox element to comply with `isRequired`.

### ISSUE THREAD

**Issue by laogao** [goxiaoy/flutter_survey_js#32]
When a checkbox question is set as `isRequired`, user has to at least check one box for the question.

**Comment by ChopinDavid** [comment]
Our team was just having this conversation. We weren't 100% sure what the behavior for `isRequired` on a checkbox would look like, but assumed that it means that at least one box must be checked for it to validate.

**Comment by laogao** [comment]
> Our team was just having this conversation. We weren't 100% sure what the behavior for `isRequired` on a checkbox would look like, but assumed that it means that at least one box must be checked for it to validate. We would maybe need to see how required checkboxes on the officially supported web frameworks behave and mimic this behavior.

This is probably best evaluated together with issue #33 . Here's what I've found out based on the JS version of survey.js:

1. When `hasSelectAll` is enabled, either this "select-all" choice is checked (which means all regular choices are checked) or any other choices are checked, the `isRequired` validation is passed;
2. When `hasNone` is enabled, either this "none" choice is checked (which means all regular choices are unchecked) or any other choices are checked, the `isRequired` validation is passed;
3. When `hasOther` is enabled, either this "other" choice is checked (which means a corresponding input box would show up) and additional input is provided, or any other choices are checked, the `isRequired` validation is passed;
4. When `hasOther` is enabled, and this "other" choice is checked, but the user hasn't yet provided additional text for the corresponding input box, the `isRequired` validation is not passed.

**Comment by laogao** [comment]
The core problem, I think, is with `RequiredValidator` from `reactive_forms`, which only marks null values and empty strings as errors, and would happily accept empty lists and maps. I've filed an issue over there https://github.com/joanpablo/reactive_forms/issues/377 . Until that gets resolved, we could have a workaround by leveraging a custom validator.

A PR is underway that provides this workaround. Next I'll see what to do with issue #33.

**Comment by laogao** [comment]
Currently the `isRequired` for checkbox element is effective in the sense that it will prevent the containing form from being submitted if the value is empty. Yet there isn't any `errorText` being displayed. The problem is likely due to the difference between standalone reactive form widgets and arrays of widgets. Maybe there is a way to wire up a `errorText` at the question level that is properly propagated by validators?
