### ISSUE TITLE
Feature: Add a means to convert single `Page` to a `Survey`

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#34]
Right now, the `SurveyWidget` takes a [`Survey`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model) object for its `survey` property. The JSON for this object might look something like this: 
```JSON
{
  "pages": [
    {
      "name": "page1",
      "title": "Single Page Survey",
      "elements": [
        {
          "type": "text",
          "name": "text_question"
        }
      ]
    }
  ]
}
```

Our team is finding that, when multi-page/pagination is disabled in our survey builder, we are getting back a [`Page`](https://surveyjs.io/form-library/documentation/api-reference/page-model) object back from the API. The JSON for this object might look something like this:
```JSON
{
    "title": "Single Page Survey",
    "elements": [
        {
          "type": "text",
          "name": "text_question"
        }
    ]
  }
```

For this reason, we wanted to create a factory constructor on the `Survey` object that would build a `Survey` from a single given `Page`. The alternative to this would be to add a factory constructor on `SurveyWidget` that takes a single given `Page`. Any properties that are shared between `Page` and `Survey` would be mapped over in a way that makes sense; for example `Page`'s `elements` property would map to `Survey`'s `questions` property. `description`, `maxTimeToFinish`, `questionsOrder`, and `title` are also properties shared between the two objects, amongst others that are not yet being mapped on the frontend (such as [`timeSpent`](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#timeSpent)).

**Comment by goxiaoy** [comment]
> Our team is finding that, when multi-page/pagination is disabled in our survey builder, we are getting back a [Page](https://surveyjs.io/form-library/documentation/api-reference/page-model) object back from the API. The JSON for this object might look something like this:

This is unreasonable, the properties in `Survey` model like `locale` is missing in such way

The latest editor https://surveyjs.io/create-free-survey will convert old version of survey json into latest, you can add another layer to convert unsupported format into `model/survey` to avoid future maintenance difficulties

**Comment by ChopinDavid** [comment]
@goxiaoy So, we learned a bit more about why this is happening. Whenever [`SurveyCreator.pageEditMode`](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#pageEditMode) is set to `single`, the JSON returned is a single `Page` object rather than a `Survey` object with an array of `Page`s.

We can handle this on our side without making changes to flutter_survey_js, but if somebody using flutter_survey_js toggles their `pageEditMode` to `single`, they will no longer be able to build a `SurveyWidget` with the outputted JSON.

We have a fix for it and although it does not address the issue of mapping a `locale` to `Survey`, this seems to be an issue with SurveyJS more than anything. We are just trying to make flutter_survey_js handle this issue as best as possible.

**Comment by laogao** [comment]
I am thinking that, if the issue is with "incompatible" JSON, and there is a one-way, lossless conversion to a "compatible" one, maybe some sort of a "preprocessor" would be more useful and less intrusive. Whether this automatic "preprocessor" should be: 1) embedded in flutter_survey_js itself, or 2) left to the user (to provide a compatible definition), is up for discussion. As of now, without changing any surface API of flutter_survey_js, I'm leaning towards the second option.
