### ISSUE TITLE
Bug: `Dropdown`s without a specified `placeholder` should default to `"Submit..."` or `"请选择..."`

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#46]
Whenever you paste
```JSON
{
 "title": "Single Page Survey",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "dropdown",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ]
}
```
into https://surveyjs.io/create-free-survey and switch to the "Preview" tab, you will notice that the `Dropdown` displays `Select...` or `请选择...` despite `"placeholder": "Select..."` not existing in the input JSON. This is how the web frameworks render this JSON as well.
### Web:
<img width="1198" alt="Screen Shot 2023-04-13 at 1 24 33 PM" src="https://user-images.githubusercontent.com/27712906/231849873-496ebc9f-3987-4e89-b9e3-1a7b726348b7.png">
<img width="1209" alt="Screen Shot 2023-04-13 at 1 52 01 PM" src="https://user-images.githubusercontent.com/27712906/231855662-e8c29258-8c14-41d7-b084-88d510415a81.png">

### Our framework:
<img width="425" alt="Screen Shot 2023-04-13 at 1 28 19 PM" src="https://user-images.githubusercontent.com/27712906/231850695-ab107f95-02ed-4177-be46-b9b57d661acc.png">

Whenever `"placeholder"` does not exist in the `Dropdown` JSON, we should default to showing `Select...` or `请选择...` for English or Chinese, respectively.

**Comment by ChopinDavid** [comment]
@goxiaoy Can you explain the process for generating the `/generated` directory?

To resolve this issue, I was going to update the `Dropdown` builder to this:
```dart
register<s.Dropdown>((context, element, {bool hasTitle = true}) {
      final e = (element as s.Dropdown);
      final placeholderString = S.of(context).placeholder;

      return ReactiveDropdownField(
        formControlName: element.name!,
        hint: Text(element.placeholder ?? placeholderString),
        items: e.choices
                ?.map(
                  (e) => DropdownMenuItem(
                    value: e.value,
                    child: Text(
                      e.text ?? e.value?.toString() ?? '',
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                  ),
                )
                .toList(growable: false) ??
            [],
      ).wrapQuestionTitle(element, hasTitle: hasTitle);
    });
```

I also updated `/l10n/intl_en.arb` to:
```JSON
{
  "nextPage": "Next Page",
  "previousPage": "PreviousPage",
  "submitSurvey": "Submit",
  "add": "Add",
  "remove": "Remove",
  "placeholder": "Select..."
}
```
and `/l10n/intl_zh.arb` to:
```JSON
{
  "nextPage": "下一页",
  "previousPage": "上一页",
  "submitSurvey": "提交",
  "add": "添加",
  "remove": "删除",
  "placeholder": "请选择..."
}
```
but was unsure what command-line command was needed to generate our `/generated` directory from these `.arb` files.

**Comment by goxiaoy** [comment]
see 
https://plugins.jetbrains.com/plugin/13666-flutter-intl
https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl

**Comment by ChopinDavid** [comment]
That makes sense. I noticed that `l10n.dart` was generated with Localizely, but didn't see Localizely in the pubspec.yaml. I was trying to generate with the vanilla Flutter intl.
