### ISSUE TITLE
Missing dependency `flutter_survey_js_model` of version 0.0.2-dev.2

### ISSUE THREAD

**Issue by laogao** [goxiaoy/flutter_survey_js#76]
The build for the main branch has been failing for some time now.

`pubspec.yaml` on main branch reads:
flutter_survey_js_model: ^0.0.2-dev.2

Yet this version is not found on pub.dev. 

P.S. I noticed several dependency updates going on under the hood, mainly around the packages like `multiple_localization` ^0.4.0, which seems to be resolved earlier today. I wonder if there are still remaining issues to be sorted out before we can fully upgrade to flutter 3.10.0?

**Comment by ChopinDavid** [comment]
Thank you so much! @laogao
