### ISSUE TITLE
How to display the saved data in edit mode?

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#79]
Hi How can we display the saved data in edit mode so that user can edit them again and submit.

**Comment by laogao** [comment]
The saved data can be set to the `answer` field of `SurveyWidget`.

**Comment by Vpdwivedi** [comment]
Yes, I tried but it gives an error.

**Comment by laogao** [comment]
> Yes, I tried but it gives an error.

I can only confirm that this mechanism works correctly for us. Could you provide more details such as the error log or screenshot of this error? Otherwise it's difficult to imagine what went wrong.

**Comment by Vpdwivedi** [comment]
Here is the code and screenshot:

toSurveyAns() {
    try {
      return {"question1": [{"Column 1": 2, "Column 2": 2, "Column 3": 2}], "question2": []}; //(mySurvey.responseJson);
    } catch(e) {
      print(e);
    }
  }

<img width="405" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/885ddc72-8336-48e3-ad56-46a74a67bcb8">


<img width="192" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/4a1e541a-2a4b-4318-9e48-70739d74eee3">

**Comment by laogao** [comment]
Please also provide the survey json (in your case the `templateJson`) used that triggered the error.

**Comment by Vpdwivedi** [comment]
Here is the JSON for templateJson

{
 "title": "Survey Form for Commune",
 "description": "Survey for commune level users",
 "logoFit": "cover",
 "logoPosition": "right",
 "pages": [
  {
   "name": "Page1",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "question1",
     "title": "Question 1",
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ]
    }
   ],
   "title": "I. COUVERTURE DES RISQUES SOCIAUX",
   "description": "Tableau001 : Couverture dela population par les mutuelles sociales toutes prestations (Une liste demutuelle sera fournie)"
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "question2",
     "title": "Question1",
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ]
    }
   ],
   "title": "1.2. Assurance Maladie Obligatoire (AMO)",
   "description": "Tableau 002 : Couverture de la population par l’AMO (interopérabilité entre le SISo et la base de la CANAM)"
  }
 ]
}

**Comment by laogao** [comment]
I managed to replicate the error. Might have something to with the way `matrixdynamic`'s answer is handled. Need more time to investigate though. Thanks for reporting.

Meanwhile maybe @goxiaoy can have a look?

**Comment by laogao** [comment]
@goxiaoy 👍

Wow, that was quick. I can verified that the fix works (used as a path dependency). Should we publish an updated version, say, `0.0.2-dev.5`?
