### ISSUE TITLE
Attempting to parse a Survey with a boolean value for showQuestionNumbers breaks the app

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#8]
Per [SurveyJS documentation](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#showQuestionNumbers), the `showQuestionNumbers` property for the `Survey` data model can be either a string or a boolean.

The following JSON will throw `Unhandled Exception: type 'bool' is not a subtype of type 'String?' in type cast` at `package:flutter_survey_js/model/survey.g.dart:55` and perpetually show a `CircularProgressIndicator`:

```JSON
{
  "title": "Software developer survey.",
  "pages": [
    {
      "elements": [
        {
          "type": "text",
          "isRequired": true,
          "name": "question 1"
        }
      ]
    }
  ],
  "showQuestionNumbers": true
}

```

This is because the JSON serializer for the `Survey` object does not handle booleans, but only strings.

**Comment by goxiaoy** [comment]
close via https://github.com/goxiaoy/flutter_survey_js/pull/9
