### ISSUE TITLE
Upgrade reactive_forms to ^15.0.0

### ISSUE THREAD

**Issue by ChopinDavid** [goxiaoy/flutter_survey_js#87]
[`ReactiveForms` was recently updated](https://github.com/joanpablo/reactive_forms/commit/15415ddf16488db2511b39986973d6e7280dcaf3) to allow `FormControl<dynamic>` to be passed as a control to `fb.group`. This would allow us to register dynamic `FormControl`s in `lib/ui/survey_element_factory.dart`, which we should be able to do given that many elements can represent either a `String` or a `num`.

Upgrading this dependency would allow me to resolve #71 because I have written some tests that ensure RadioGroup can handle being provided either an `int` or a `String`.

**Comment by ChopinDavid** [comment]
I went ahead and created [this PR](https://github.com/artflutter/reactive_forms_widgets/pull/102) in an effort to resolve this issue without having to use `dependency_overrides:`. Will be able to resolve this issue once that PR is merged...

**Comment by laogao** [comment]
`reactive_forms` ^15.0.0 introduced a breaking change (among others): `validators` are now of type `List<Validator<dynamic>>` instead of `List<ValidatorFunction>`.

When we upgrade to ^15.0.0, we need to take care of this API change in `lib/ui/validators.dart`.

**Comment by ChopinDavid** [comment]
@laogao You're correct, but this seems like a simple fix. Basically, our validators were previously `ValidatorFunction`s, a typedef of `Map<String, dynamic>? Function(AbstractControl<dynamic> control)`.

The change to ^15.0.0 is simple. Anything that is currently a `ValidatorFunction` will turn into an implementation of the new, abstract `Validator` class. We can override the `validate` method, which takes an `AbstractControl<T>` as an argument and returns `Map<String, dynamic>?`, much like our current `ValidatorFunction`s.

For example, [`lib/ui/validators.dart`, lines 57-65](https://github.com/goxiaoy/flutter_survey_js/blob/c2032360a4e239a947c7c3abea08e219e5403a14/lib/ui/validators.dart#L57-L65) could go from looking like this:
```dart
res.add((control) {
  if (control.value is String) {
    if (!value.allowDigits! &&
    (control.value as String).contains('.')) {
      return {'allowDigits': value.allowDigits};
    }
  }
  return null;
});
```
to looking like this:
```dart
res.add(AllowDigitsValidator(value.allowDigits!))
```
where `AllowDigitsValidator` looks something like this:
```dart
class AllowDigitsValidator extends Validator {
  AllowDigitsValidator(this.allowDigits);
  final bool allowDigits;
  @override
  Map<String, dynamic>? validate(AbstractControl control) {
    // TODO: implement validate
    if (control.value is String) {
      if (!allowDigits && (control.value as String).contains('.')) {
        return {'allowDigits': allowDigits};
      }
    }
    return null;
  }
}
```
and, of course, [`res`](https://github.com/goxiaoy/flutter_survey_js/blob/c2032360a4e239a947c7c3abea08e219e5403a14/lib/ui/validators.dart#LL34C3-L34C37) is now `List<Validator>` instead of `List<ValidatorFunction>`.

**Comment by laogao** [comment]
@ChopinDavid 

Yup. I'm not saying it's complex or anything. Just that there is a breaking change in 15.0.0 we'll have to deal with.

On a side note, this issue (https://github.com/joanpablo/reactive_forms/issues/377) probably needs more commentary from someone other than me. In case you're interested.

**Comment by ChopinDavid** [comment]
@laogao I'm trying to follow the issue, but there's a lot to take in there. Which issue in our project are we trying to resolve with that proposed change? I'm trying to understand why `ValidationMessage.minLength` doesn't take care of whatever we need.

**Comment by laogao** [comment]
@ChopinDavid 

Say we have a text field that records a `num`, if `minLength` were used, valid values such as `0`, `1`, `42`, `2.0`, etc. would not pass.

**Comment by laogao** [comment]
Ultimately this can be circumvented via a custom validator, the approach we've taken in https://github.com/goxiaoy/flutter_survey_js/issues/32 . If that PR got accepted, we no longer have to supply and maintain our own `NonEmptyValidator`. It would also have the extra benefit of a single validation message key, namely `ValidationMessage.requiredNonEmpty`, to match `isRequired` in `survey.js`.

**Comment by ChopinDavid** [comment]
Closing as not needed.
