### ISSUE TITLE
Can we hide pagination dots for mobile?

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#88]
Can we hide pagination dots that come on the top of the screen. Screenshot is attached for the reference:

<img width="184" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/0fdf6977-8988-443f-b681-bcacc740716b">

Also can we change the text/color of buttons?

**Comment by laogao** [comment]
There is a `stepperBuilder` field in `SurveyLayout` which maybe you can override.

As for the theming of widgets, you may wrap your entire `SurveyWidget` in a flutter `Theme` widget and use its `data` field to customize the colors. (see #14)

**Comment by goxiaoy** [comment]
See https://github.com/goxiaoy/flutter_survey_js/blob/main/example/lib/components/custom_layout.dart
