### ISSUE TITLE
With reference #79 issue, I am getting type '_Map<dynamic, dynamic>' is not a subtype of type 'Map<String, Object?>?' this error

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#89]
Dear,

I am getting type '_Map<dynamic, dynamic>' is not a subtype of type 'Map<String, Object?>?' while sending answer. with the reference of #79 issue.

**Comment by goxiaoy** [comment]
Please follow the Bug report template to create bug issues.

And the answer accepts `Map<String, Object?>` not  `_Map<dynamic, dynamic>`. You should check your parameter type.
see https://stackoverflow.com/questions/31257735/what-is-the-difference-between-dynamic-and-object-in-dart

**Comment by Vpdwivedi** [comment]
But I am sending the same response data only what I am getting from Submit function.

**Comment by goxiaoy** [comment]
@Vpdwivedi 
Please provide more information as the Bug report template says.
Can not help you without steps to reproduce

**Comment by Vpdwivedi** [comment]
Thank you fixed in #91
