### ISSUE TITLE
Support for expression

### ISSUE THREAD

**Issue by goxiaoy** [goxiaoy/flutter_survey_js#90]
The surveyjs javascript use  [pegjs](https://github.com/pegjs/pegjs) to parse expression, and use condition runner to provide logic features

- triggers
    - runexpression
- calculatedValues
- question logic
    -  visibleIf
    - enableIf
    - defaultValueExpression
    - choicesVisibleIf
    - choicesEnableIf
- question type
    - expression
    
original codes : 
https://github.com/surveyjs/survey-library/tree/master/src/expressions
https://github.com/surveyjs/survey-library/blob/master/src/conditions.ts
https://github.com/surveyjs/survey-library/blob/master/src/conditionsParser.ts
https://github.com/surveyjs/survey-library/blob/master/src/conditionProcessValue.ts

Paths to achieve this
| Index| Path|Desc| Implement difficulty| Maintain difficulty |
|  ----|  ----  |----  | ----  | ----  |
|  1| Fully rewrite with dart | 💪  | ⭐⭐⭐⭐⭐  | ⭐⭐⭐⭐⭐ |
| 2| Use js engine in dart | Build tools to convert original js codes to single file. and run as [js in dart](https://github.com/abner/flutter_js) | ⭐⭐⭐⭐ | ⭐⭐|
| 3| Rewrite with [antlr4](https://github.com/antlr/antlr4) | rewrite expression parser with antlr4,  | ⭐⭐⭐⭐  | ⭐⭐⭐ |
| 4| Use WebAssembly (WASM)| compile js into WASM and embed it into Flutter  | Unknown  | Unknown   |

**Comment by laogao** [comment]
Is it possible to take advantage of existing dart parsers out there such as https://pub.dev/packages/expressions or the more fundamental https://pub.dev/packages/petitparser ?

**Comment by goxiaoy** [comment]
@laogao Thanks for your reference. We need more time to investigate those packages, and they might help us to reduce the implementation and maintainance difficulty of path 1

**Comment by ChopinDavid** [comment]
I've researched PEG a bit. petitparser came up during my research. From my investigation, there didn't seem to be many good dart PEG parsers. But finding one would make implementing conditions pretty seamless.

**Comment by goxiaoy** [comment]
implemented with js engine. would close via 3b6eb9a8274a16876dfcdac3ad6e4254f20b97ee
