### ISSUE TITLE
Date values should be `jsonEncode`-able

### ISSUE THREAD

**Issue by laogao** [goxiaoy/flutter_survey_js#92]
**Describe the bug**
When submitting a survey with dates, the answer is currently not `jsonEncode`-able. Instead, the following error will be thrown:
```
errors.dart:288 Uncaught (in promise) Error: Converting object to an encodable object failed: Instance of 'DateTime'
```

**To Reproduce**
SurveyJs json
```json
{
    "title": "datetime jsonEncode issue",
    "logoPosition": "right",
    "pages": [
        {
            "name": "page1",
            "elements": [
                {
                    "type": "text",
                    "name": "102 visit date",
                    "title": "Visit Date",
                    "isRequired": true,
                    "inputType": "date"
                }
            ]
        }
    ],
    "showQuestionNumbers": "off"
}
```
SurveyJs answer
```json
{"102 visit date": 2023-06-07 00:00:00.000}
```

**Expected behavior**
The answer is properly encoded in JSON:
```
  onSubmit: (v) async {
    print(jsonEncode(v));
  },
```
Here's how `surveyjs.io` handles the same input:
```json
{"102 visit date": "2023-06-07"}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS/Web
 - Browser: Chrome

**Comment by laogao** [comment]
This issue could be circumvented by suppying a custome encoder to `jsonEncode`:

```dart
  dynamic encodeDateTime(dynamic item) {
    if (item is DateTime) {
      return item.toIso8601String();
    }
    return item;
  }
```

This would give us something like:

```
{"102 visit date":"2023-06-07T00:00:00.000"}
```

Ideally, we could do better at library level by storing the value in `String` in the first place (as `surveyjs.io` apparently does) and according to its `inputType` (in this particular case, a `date` without the `time` part).

**Comment by goxiaoy** [comment]
It's a very common dart issue. Should keep it as `DateTime` for further calculation like `expression`

**Comment by laogao** [comment]
> It's a very common dart issue. Should keep it as `DateTime` for further calculation like `expression`

I understand the thinking behind this. That said, since `DateTime`s and `String`s are inter-convertible, I see three reasons why we might prefer an underlying string representation (and accept the inconvenience and overhead of coverting the values back and forth for calculation):

1. This is how the official `surveyjs.io` treats `date` inputs for text fields.
2. One would have a hard time making his/her answers compatible with `surveyjs.io` before submitting. Within the answer value itself, there's nothing indicating clearly about the `type` and `inputType` of the survey question. (In our case it's a date, not a timestamp.) He/she'll have to look into the survey definition to find out.
3. Sometimes answers are provided from elsewhere, possibly from some app built with `surveyjs.io`. The value will be provided in string format and somehow needs to be converted back to `DateTime`, or not. It's usually hard to be sure.
