### ISSUE TITLE
Bug - Error while changing the App language from English to French

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#95]
Getting the following error while setting up the language as French

<img width="192" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/df158d61-09c5-4639-9081-644aa010fed0">

Below is the code for Applocalization

<img width="746" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/a9ab2d7f-1162-4b94-a582-9b4860432cc7">

**Comment by laogao** [comment]
As of now, locales of `en` and `zh` are (dare I say partially) supported out-of-the-box. If you wish, you could make contributions to this project by providing the necessary .arb files etc. and submitting a PR.

![image](https://github.com/goxiaoy/flutter_survey_js/assets/68553/27b167a9-3efd-4721-bed2-3e0c6d85eb1e)

You may also want to checkout the following IDE plugins during the process:
[flutter-intl for IntelliJ](https://plugins.jetbrains.com/plugin/13666-flutter-intl)
[localizely for VS Code](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl)

**Comment by Vpdwivedi** [comment]
Dear @laogao 
Thank you for your response. I tried to setup but facing some version compatibility issues. Shall I provide you a Translation file in French and you add the same. Will this work for you?

**Comment by laogao** [comment]
@Vpdwivedi sure. let's see what we can do.

**Comment by Vpdwivedi** [comment]
@laogao please find attached translation file of French.
[intl_fr.zip](https://github.com/goxiaoy/flutter_survey_js/files/12011453/intl_fr.zip)
