### ISSUE TITLE
Error with version flutter_survey_js-0.0.2-dev.5 for answer data

### ISSUE THREAD

**Issue by Vpdwivedi** [goxiaoy/flutter_survey_js#97]
I am getting this error while sending the answer data for Dynamix Matrix with (flutter_survey_js-0.0.2-dev.5) however the same response data is working obsoletely fine with version (flutter_survey_js-0.0.2-dev.4)

This is the response data we have saved in our Database:
{"TABL001":[{"ASSURE_AMO_CHARGE_MED~N~M":null,"Column 2":3,"Column 3":null}],"TABL002A":{"INPS_A":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 2":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 3":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 4":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 5":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 6":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 7":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 8":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null}},"question2":{"INPS_A":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 2":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 3":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 4":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 5":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 6":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 7":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null},"Row 8":{"ASSURE_AMO~N~M":null,"ASSURE_AMO~N~F":null}},"question1":null}

Below is the error that we get

![Screenshot_20230711-121806](https://github.com/goxiaoy/flutter_survey_js/assets/17593248/7246eebb-c935-4b49-8439-399a5ffbe191)

Code to convert string to JSON and pass to survey.
/// Return data for survey answer
  toSurveyAns() {
    try {
      if(mySurvey != '' && mySurvey != null && mySurvey.responseJson != '' && mySurvey.responseJson != null) {
        return json.decode(mySurvey.responseJson);
      } else {
        return null;
      }
    } catch(e) {
      print(e);
    }
  }

<img width="385" alt="image" src="https://github.com/goxiaoy/flutter_survey_js/assets/17593248/ffbd33b8-ffc6-4bc8-acf8-b45c4d513cb6">

**Comment by goxiaoy** [comment]
Could you please follow the bug report issue template to create bug report?
We need the minimum SurveyJs json and answer to reproduce this bug. Thanks

**Comment by Vpdwivedi** [comment]
Created a separate issue using the bug report template. Closing this one. Thanks
